# Generated by Django 2.2 on 2020-03-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Reference', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('Phone', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('Note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
