# Generated by Django 2.2 on 2020-04-02 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0015_auto_20200402_1941'),
        ('clients', '0007_client_user'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='Client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientorderlist', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientorderlist', to='products.Product'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='Quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='Status',
            field=models.CharField(choices=[('en attente', 'en attente'), ('livré', 'livré')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClientOrderlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Status',
            field=models.CharField(choices=[('en attente', 'en attente'), ('livré', 'livré')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierOrderlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
