# Generated by Django 2.2 on 2020-04-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200402_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
