# Generated by Django 2.2 on 2020-04-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200403_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierorder',
            old_name='Product',
            new_name='Products',
        ),
    ]
