# Generated by Django 2.2 on 2020-04-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200411_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierorder',
            old_name='Products',
            new_name='Product',
        ),
    ]
