# Generated by Django 2.2 on 2020-04-11 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_stocktrack_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_auto_20200411_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientorder',
            old_name='Quantity',
            new_name='Total',
        ),
        migrations.RenameField(
            model_name='supplierorder',
            old_name='Quantity',
            new_name='Total',
        ),
        migrations.RemoveField(
            model_name='clientorder',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='Product',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierorderlist', to='products.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='Orders',
            field=models.ManyToManyField(to='orders.Order'),
        ),
    ]
