# Generated by Django 2.2 on 2020-04-12 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_stocktrack_user'),
        ('neworders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nOrderC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norderclist', to='products.Product')),
                ('nClientOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norderclist', to='neworders.nClientOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norderclist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nOrderS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norderslist', to='products.Product')),
                ('nSupplierOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norderslist', to='neworders.nSupplierOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norderslist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='nOrder',
        ),
    ]
