# Generated by Django 2.2 on 2020-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
