# Generated by Django 2.2 on 2020-03-26 20:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200326_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Particulier'), (2, 'Entreprise')], max_length=1),
        ),
    ]
