# Generated by Django 2.2 on 2020-03-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200326_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='First_name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='client',
            name='Type',
            field=models.CharField(choices=[(1, 'Particulier'), (2, 'Entreprise')], max_length=30),
        ),
    ]
