# Generated by Django 2.2 on 2020-03-26 20:12

from django.db import migrations
import multiselectfield.db.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200326_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Particulier'), (2, 'Entreprise')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='Phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
