# Generated by Django 2.2 on 2020-04-12 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0007_client_user'),
        ('products', '0017_stocktrack_user'),
        ('suppliers', '0004_supplier_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='nClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Status', models.CharField(choices=[('en attente', 'en attente'), ('livré', 'livré')], max_length=20, null=True)),
                ('Client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nclientorderlist', to='clients.Client')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nclientorderlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nSupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Status', models.CharField(choices=[('en attente', 'en attente'), ('livré', 'livré')], max_length=20, null=True)),
                ('Supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsupplierorderlist', to='suppliers.Supplier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsupplierorderlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='nOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsupplierorderlist', to='products.Product')),
                ('nClientOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nclientorderlist', to='neworders.nClientOrder')),
                ('nSupplierOrder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nsupplierorderlist', to='neworders.nSupplierOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norderlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
