# Generated by Django 2.2 on 2020-04-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neworders', '0002_auto_20200412_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='nclientorder',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='nsupplierorder',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
