# Generated by Django 2.2 on 2020-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20200326_2127'),
        ('products', '0003_auto_20200326_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Suppliers',
            field=models.ManyToManyField(to='suppliers.Supplier'),
        ),
    ]
