# Generated by Django 2.2 on 2020-03-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_user'),
        ('products', '0009_auto_20200330_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Suppliers',
        ),
        migrations.AddField(
            model_name='product',
            name='Suppliers',
            field=models.ManyToManyField(to='suppliers.Supplier'),
        ),
    ]
