# Generated by Django 2.2 on 2020-03-31 18:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200331_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Suppliers',
        ),
        migrations.AddField(
            model_name='product',
            name='Suppliers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Delll', 'Delll'), ('LGG', 'LGG'), ('fhd3333', 'fhd3333'), ('bzebz', 'bzebz'), ('sfbsb', 'sfbsb'), ('qsd', 'qsd'), ('benouda', 'benouda'), ('moh', 'moh'), ('Sony', 'Sony'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('jhgjgjv', 'jhgjgjv'), ('zgbzet', 'zgbzet'), ('jrey', 'jrey'), ('HP', 'HP'), ('azdazd', 'azdazd'), ('hesgbhke', 'hesgbhke'), ('afaefzf', 'afaefzf')], default=None, max_length=107),
            preserve_default=False,
        ),
    ]
