# Generated by Django 2.2 on 2020-03-31 18:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200331_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Suppliers',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
