# Generated by Django 2.2 on 2020-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_user'),
        ('products', '0014_auto_20200402_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Suppliers',
        ),
        migrations.AddField(
            model_name='product',
            name='Suppliers',
            field=models.ManyToManyField(to='suppliers.Supplier'),
        ),
    ]
