# Generated by Django 2.2 on 2020-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200413_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
