# Generated by Django 2.2 on 2020-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(default='DESC'),
        ),
        migrations.AddField(
            model_name='service',
            name='ico',
            field=models.ImageField(default='NULL', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='TITLE', max_length=100),
        ),
    ]
