# Generated by Django 2.2 on 2020-03-30 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], max_length=30)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('Reference', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('Note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zsupplierlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
