# Generated by Django 2.2 on 2020-04-02 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0004_supplier_user'),
        ('products', '0015_auto_20200402_1941'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('en attente', 'en attente'), ('livré', 'livré')], max_length=1)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierorderlist', to='products.Product')),
                ('Supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierorderlist', to='suppliers.Supplier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
