# Generated by Django 2.2 on 2020-04-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200402_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
