# Generated by Django 2.2 on 2020-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200402_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='Status',
            field=models.CharField(choices=[('en attente', 'en attente'), ('livré', 'livré')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='Status',
            field=models.CharField(choices=[('en attente', 'en attente'), ('livré', 'livré')], max_length=20, null=True),
        ),
    ]
