# Generated by Django 2.2 on 2020-04-03 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200402_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientorderlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierorderlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
