# Generated by Django 2.2 on 2020-04-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200411_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='Orders',
            field=models.ManyToManyField(to='orders.Order'),
        ),
    ]
