# Generated by Django 2.2 on 2020-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20200326_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='Type',
            field=models.CharField(choices=[('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], max_length=30),
        ),
    ]
