# Generated by Django 2.2 on 2020-03-28 14:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200326_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Suppliers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sony', 'Sony'), ('Asus', 'Asus'), ('Acer', 'Acer'), ('Dell', 'Dell'), ('HP', 'HP')], max_length=22),
        ),
    ]
