# Generated by Django 2.2 on 2020-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_user'),
        ('products', '0012_auto_20200331_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Suppliers',
        ),
        migrations.AddField(
            model_name='product',
            name='Suppliers',
            field=models.ManyToManyField(to='suppliers.Supplier'),
        ),
    ]
