# Generated by Django 2.2 on 2020-04-02 16:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200402_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Suppliers',
        ),
        migrations.AddField(
            model_name='product',
            name='Suppliers',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Asus', 'Asus'), ('SPREE', 'SPREE'), ('HANZ', 'HANZ'), ('Delll', 'Delll'), ('LGG', 'LGG'), ('fhd3333', 'fhd3333'), ('bzebz', 'bzebz'), ('sfbsb', 'sfbsb'), ('qsd', 'qsd'), ('benouda', 'benouda'), ('moh', 'moh'), ('Sony', 'Sony'), ('Acer', 'Acer'), ('HP', 'HP'), ('azdazd', 'azdazd'), ('hesgbhke', 'hesgbhke'), ('afaefzf', 'afaefzf')], default=0, max_length=98),
            preserve_default=False,
        ),
    ]
