# Generated by Django 2.2 on 2020-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200402_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('Date', models.DateField(null=True)),
            ],
        ),
    ]
