# Generated by Django 2.2 on 2020-05-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200419_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktrack',
            name='In',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stocktrack',
            name='Out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
